extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
env:
  es6: true
  node: true
  protractor: true
  jasmine: true
globals:
  ExpectedConditions: false
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
